name: 'AWS region reduction map'
description: 'Converts AWS region names from full names to either "fixed" or "short" abbreviations'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  region:
    required: true
    description: "Input region code"
  format:
    required: false
    description: |-
      Format convert to. Valid values ('long', 'short', 'fixed'). 
      If empty short and fixed inputs are converted to long, long inputs are converted to fixed.
outputs:
  result:
    description: "Converted AWS region"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REGION: ${{ inputs.region }}
    FORMAT: ${{ inputs.format }}